# Generated by Django 5.1.7 on 2025-04-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise_assistant", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="knowledge",
            name="title",
        ),
        migrations.AlterField(
            model_name="knowledge",
            name="department",
            field=models.CharField(default="未分類", max_length=255),
        ),
        migrations.AlterField(
            model_name="knowledge",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
