# Generated by Django 5.1.7 on 2025-04-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general_assistant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="chunk",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
